######################################################################
# Automatically generated by qmake (3.0) Fri Jan 11 11:15:34 2019
######################################################################

TEMPLATE = app
TARGET = AnimeList
INCLUDEPATH += .

QMAKE_CXXFLAGS += -std=c++11

# Input
SOURCES += AnimeList.cpp
SOURCES += MainWindow.cpp
SOURCES += file_handler.cpp
SOURCES += AddWindow.cpp
SOURCES += SelectWindow.cpp
SOURCES += SortWindow.cpp

QT += widgets

